"""Per-repository template for tools/build_notebook.py (NOTEBOOK_SPEC 2.0 §4 standalone carrier).

Only the task-specific prose and stage cells live here. Runtime install, the embedded pipeline
modules (pipeline.py, metrics.py, samples.py), and the model pin/stage/verify cells are produced by
the generator from repository sources so they cannot drift from the package.

This template configures an E2E supervised-adaptation workflow: the pinned Depth Anything V2 Small snapshot
is digest-verified and loaded, a digest-pinned real RGB-D corpus (40 DIODE validation views with metric
depth) is fetched, validated and split by scan, the inference contract is exercised on a real view with a
metric reference (the first `sample-sanity` evaluation report of this repository), the untouched checkpoint
is scored on the test split beside two trivial priors (the zero-shot policy), the DPT neck and head are
trained on the frozen backbone (the frozen policy) and then the last blocks with them (the unfrozen policy),
the policy ladder is selected on validation, the held-out split is scored, and the adapter is exported and
reloaded.
"""
# ruff: noqa: E501  -- markdown prose and code-cell text are kept on single lines for readable rendering

TEMPLATE = {
    "package": "depth_anything_depth_estimation_pipeline",
    "repo_name": "depth-anything-depth-estimation-pipeline",
    "stem": "depth_anything_depth_estimation",
    "notebook_name": "depth_anything_depth_estimation_colab.ipynb",
    "profile": "E2E",
    "mode": "GUIDED",
    # GDL11 (NOTEBOOK_SPEC 2.2 §3.5): Sections 1-3 labelled Infrastructure and the carried module source collapsed.
    "infrastructure_labels": True,
    "isolated_runtime": True,
    # The fleet's uv isolated-environment mechanism (bart-mnli-zero-shot-classification-pipeline ee128d2, generator /2.1):
    # managed CPython, a size- and SHA-256-verified uv wheel (the same wheel as this repository's workshop notebook), and a
    # lock compiled from the pyproject pins with `uv pip compile pyproject.toml --python-version 3.12 --python-platform
    # x86_64-manylinux_2_28 --generate-hashes --only-binary :all: -o tutorials/requirements-colab.lock.txt`, transitive
    # versions constrained to the workshop's carried requirements.txt.
    "managed_python": "3.12.12",
    "uv": {
        "version": "0.12.15",
        "url": "https://files.pythonhosted.org/packages/1e/fd/432451d732917c49152a291de3ef171aa6b0f1a22d39780fb2c1f085ca4c/uv-0.12.15-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        "bytes": 20081404,
        "sha256": "aee9802f46bae436bd91751bb33ddeb379ef1596b5c19df193219d545d244b60",
    },
    "lock": "tutorials/requirements-colab.lock.txt",
    "run_all": (
        "Selecting **Run all** in a fresh supported runtime builds an isolated environment from the hash-locked pins (the "
        "kernel's own packages are left alone, so no restart is needed), stages and digest-verifies the "
        "pinned Depth Anything V2 Small snapshot (safetensors, 99 MB), fetches 40 digest-pinned DIODE validation views — "
        "RGB, metric depth and validity mask, 312 MB in total — by pinned byte ranges of the Marigold evaluation dataset archive at ETH Zürich (no credential), validates "
        "them and draws 24 / 8 / 8 training, validation and test views by a seeded split of whole scans, runs one test view "
        "through the inference contract with an input manifest, a rejection probe and a `sample-sanity` evaluation report "
        "against its metric reference, scores the untouched checkpoint on the test split beside a constant prior and a "
        "vertical-gradient prior (the **zero-shot policy**), trains the DPT neck and head on the frozen backbone (the "
        "**frozen policy**) and then the last two transformer blocks with them (the **unfrozen policy**), selects the "
        "policy ladder's best epoch by validation AbsRel — where epoch 0 is the untouched checkpoint — scores the held-out "
        "split with the selected model, renders depth maps before and after, exports the trained tensors as safetensors "
        "with a manifest, and reloads that artifact into a fresh pipeline to verify parity. The default path needs no "
        "repository clone, no DIMER worker or service, no credential, no upload dialog and no configuration edit "
        "(NOTEBOOK_SPEC 2.2 §5). CUDA is used when present; a GPU runtime is recommended. Measured: 725.3 s for the whole "
        "notebook on a fresh Colab Tesla T4 (2026-10-03; 605.0 s of it the corpus fetch), 249.7 s of model cells on a "
        "24-thread Windows workstation CPU (2026-10-03, files pre-staged). A hosted CPU runtime is unmeasured; expect "
        "several times the workstation time (an estimate, not a measurement)."
    ),
    "byod": (
        "After the tutorial workflow completes, set `USE_BYOD = True` in Section 4, select that cell and choose **Runtime → "
        "Run after** (it re-runs Section 4 and every later cell; Sections 5, 6 and 7 reload the pretrained model first, so "
        "the earlier adaptation never carries over into the *zero-shot* numbers). Supply your own RGB-D records through the "
        "upload dialog on Colab, or as a path in `BYOD_PATH` (a `.zip` or a directory) on any runtime: `records.csv` "
        "(columns `id`, `image`, `depth`, `group`, optional `mask`; `group` — the scan, session or device — must be non-empty "
        "on every row, or the loader refuses the set) beside the image files and `.npy` arrays (depth in metres, mask "
        "boolean); files in a `.zip` are decoded from the archive, never extracted to disk. The set needs at least **4 "
        "distinct groups** (one for test, one for validation, at least two for training) and at least 4 training views; "
        "Section 4 checks both and names the split it refuses. The records pass through the same validation, seeded "
        "group-disjoint split, priors, zero-shot scoring, policy ladder, held-out evaluation, preview, artifact export and "
        "reload-parity cells as the DIODE sample. The expected schema and the ceilings are stated in the Prerequisites and "
        "in Section 4, and uploaded files stay inside this runtime. BYOD is optional and never part of the default path."
    ),
    "pipeline_class": "DepthAnythingPipeline",
    "weights_key": "depth-anything-v2-small",
    "modules": ["pipeline.py", "metrics.py", "samples.py"],
    "entry_module": "pipeline.py",
    "identity_names": {},
    "runtime_imports": ["torch", "transformers"],
    "title": "Depth Anything V2 Small — DIMER E2E supervised adaptation tutorial: zero-shot vs neck/head vs bounded unfreeze on DIODE (standalone)",
    "badges": [
        (
            "GitHub",
            "https://img.shields.io/badge/GitHub-181717?style=flat&logo=github&logoColor=white",
            "https://github.com/kurtvalcorza/depth-anything-depth-estimation-pipeline",
        ),
        (
            "Open In Colab",
            "https://colab.research.google.com/assets/colab-badge.svg",
            "https://colab.research.google.com/github/kurtvalcorza/depth-anything-depth-estimation-pipeline/blob/main/tutorials/depth_anything_depth_estimation_colab.ipynb",
        ),
        (
            "Hugging Face",
            "https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-depth--anything%2FDepth--Anything--V2--Small--hf-ffcc4d?style=flat",
            "https://huggingface.co/depth-anything/Depth-Anything-V2-Small-hf",
        ),
        (
            "Upstream",
            "https://img.shields.io/badge/Upstream-DepthAnything%2FDepth--Anything--V2-181717?style=flat&logo=github&logoColor=white",
            "https://github.com/DepthAnything/Depth-Anything-V2",
        ),
        ("arXiv", "https://img.shields.io/badge/arXiv-2406.09414-b31b1b.svg", "https://arxiv.org/abs/2406.09414"),
    ],
    "capability": "monocular relative depth estimation from one RGB still image and bounded supervised adaptation — the DPT neck and head on the frozen backbone with an optional unfreeze of the last transformer blocks, selected on validation against the untouched checkpoint — measured by affine-aligned AbsRel and δ1 against metric depth, using the pinned Depth Anything V2 Small weights",
    "intro": (
        "At inference the image is rescaled so its sides are multiples of 14 near 518 px, passed through the DINOv2 "
        "ViT-S/14 backbone and the DPT neck and head, and the raw prediction is interpolated back to the input "
        "resolution: a per-pixel map of **relative inverse depth** — larger is nearer, the scale and shift are unknown, "
        "and the values are **not metres**. The carried pipeline module adds manifest verification, input validation "
        "with named ceilings, the resize back to the input resolution, and the `abs_rel`, `validate_inputs` and "
        "`evaluation_report` helpers; `evaluation_report` becomes `sample-sanity` only when a caller supplies metric "
        "reference depth — which this notebook, unlike its inference-only predecessor, does.\n\n"
        "What this notebook adds to inference is **supervised adaptation under an explicit policy ladder**. The "
        "dataset is real and carries metric ground truth: 40 views from the DIODE validation release (CC BY 4.0) — the "
        "first two views of each of its 20 laser-scanned scenes, 10 indoor and 10 outdoor — pinned per file by byte "
        "size and SHA-256 and read by HTTP Range requests at pinned offsets of the uncompressed DIODE validation tar in the Marigold evaluation dataset archive (ETH Zürich), "
        "fetched at run time and refused on any mismatch. Views of one scan share a scene, so the sample is split by "
        "**scan**, never by view. The carried `metrics.py` scores a prediction by **AbsRel** and **δ1** after a "
        "per-image least-squares alignment of the prediction to inverse reference depth (the standard protocol for a "
        "relative-depth model, with the far cap at 350 m); a **constant prior** (the image's own median depth) and a "
        "**vertical-gradient prior** (nearer at the bottom) frame the numbers. The **zero-shot policy** is the "
        "checkpoint as published; the **frozen policy** trains the DPT neck and head (2.7 M parameters) on the frozen "
        "backbone under a scale-and-shift-invariant loss; the **unfrozen policy** continues by training the last two "
        "transformer blocks with them; the epoch with the lowest validation AbsRel is kept — epoch 0, the untouched "
        "checkpoint, competes on equal terms, so the honest outcome \"do not adapt\" is available. The adaptation "
        "question is whether 24 DIODE training views buy anything over a model trained on 62 million images. Nothing "
        "here is a quality claim about your images: it is one seeded split of one small corpus.\n\n"
        "**Who this is for.** A learner who knows basic Python and NumPy, has met the idea of a neural network, and "
        "wants to see how a pretrained depth model is measured and adapted to new data without fooling themselves. No "
        "prior experience with depth estimation, Depth Anything or fine-tuning is assumed; each term is explained where "
        "it is first used and again in the **Glossary** at the end.\n\n"
        "**Input → Model → Output.**\n\n"
        "| | Inference | Adaptation |\n"
        "|---|---|---|\n"
        "| Input | one RGB image, sides 14..4,096 px | 24 / 8 training and validation views, each an RGB image with a metric depth map and a validity mask |\n"
        "| Model | Depth Anything V2 Small: DINOv2 ViT-S/14 backbone + DPT neck and head | the same model; the DPT neck and head, then also the last `TRAINABLE_BLOCKS` backbone blocks, trained |\n"
        "| Output | an H × W map of relative inverse depth (larger = nearer, not metres) | the selected policy, held-out AbsRel / δ1 against two priors and the checkpoint, and a safetensors adapter that reloads with parity |\n\n"
        "**How to use this notebook.** Choose a runtime (a GPU runtime is much faster; CPU works), then **Runtime → Run "
        "all**. Sections 1–3 are **infrastructure** — the isolated environment, the carried code (collapsed) and the "
        "model verification — and can be run without study. The learning path starts in Section 4. Form fields "
        "(`# @param`) are the only values meant to be edited; the defaults reproduce the recorded path. Each stage states "
        "what it does and asks you to **predict** before it runs; the next cell opens with **What to notice** and a "
        "collapsible **Check your reasoning** block with a worked answer from a recorded run. Sections 5, 6 and 7 always "
        "start from the pretrained model, so any re-run (BYOD or an experiment) compares against the untouched "
        "checkpoint. Section 10 is a **change-one-thing activity**; each optional experiment names the cell to change "
        "and the cell to re-run from (**Runtime → Run after**). **Troubleshooting**, a **Glossary** and a **Conclusion** "
        "template are at the end. Your notes are optional and are not required submissions.\n\n"
        "**Roadmap:** 4 fetch, validate and split the corpus by scan → 5 predict one view through the inference contract "
        "→ 6 two priors and the untouched checkpoint (zero-shot) → 7 the policy ladder, selected on validation → 8 "
        "compare on the held-out scans → 9 depth maps before and after, export and reload → 10 **change one thing: the "
        "learning rate** → conclude."
    ),
    "learning_objectives": (
        "by the end you should be able to (1) explain *RGB image → backbone, DPT neck and head → relative inverse depth* "
        "and say why the map is not in metres (Section 5); (2) explain why a relative prediction is least-squares aligned "
        "before AbsRel and δ1 are computed, and read those two numbers (Sections 5–6); (3) explain from Section 6's "
        "numbers why the two priors frame the checkpoint's score; (4) predict and then check which policy the validation "
        "split selects and what it buys on held-out scans (Sections 7–8); (5) explain why the split is by scan, never by "
        "view, and why validation, never test, chooses the kept epoch; (6) predict and then measure how a different "
        "learning rate changes the selected policy (Section 10); and (7) check that an exported adapter reproduces the "
        "evaluated model (reload parity, Section 9). Along the way the notebook stages and digest-verifies the pinned "
        "snapshot and fetches a digest-pinned real RGB-D corpus."
    ),
    "exclusions": (
        "metric (absolute) depth, video or temporal depth, stereo or multi-view fusion, surface normals, 3D "
        "reconstruction, batch inference, data augmentation, full-backbone or patch-embedding training, and any claim "
        "that 20 DIODE scenes stand in for your images. The repository exposes none of these; an adapted model still "
        "emits relative inverse depth."
    ),
    "prerequisites": [
        "- **Learner:** basic Python and NumPy, and Colab or Jupyter familiarity; no prior experience with depth estimation or fine-tuning. The notebook explains inverse depth, the least-squares alignment, AbsRel and δ1, the DPT neck and head, the three policies and epoch 0 where they are first used; the Glossary repeats them.",
        "- **Runtime:** a fresh supported runtime (Google Colab, Kaggle or Linux Jupyter — **Linux x86_64 only**; the notebook builds its own isolated Python 3.12.12 environment, and a Windows or macOS kernel is not supported). The default path runs on CPU and uses CUDA automatically when available, float32 on both; a GPU runtime is recommended. Measured, each figure with its environment: in a local Windows CPU pre-flight (2026-09-19, CPython 3.12.10, float32, files pre-staged) predicting one 1024 × 768 view took 0.37 s, the 8-view zero-shot test score 3.2 s and the five-epoch ladder over 24 views 92.6 s; a review run on a 24-thread Windows workstation CPU (2026-10-03) took 204.1 s for the same ladder; on a fresh Colab Tesla T4 session (2026-10-03) the ladder took 24.0 s and the whole notebook 725.3 s, most of it the corpus fetch. No hosted CPU run is recorded; on a 2-vCPU hosted CPU runtime expect the ladder to take several times the workstation figure (an estimate). The locked install (PyTorch 2.14.0 with its CUDA libraries) and the 99 MB checkpoint are the large downloads of the run, then the 312 MB of DIODE files.",
        "- **Knowledge:** basic Python and NumPy; the difference between inverse depth (larger = nearer, arbitrary scale and shift) and metric distance; why a least-squares alignment is needed before a relative prediction can be scored against metres; what AbsRel and δ1 measure; what validation-based selection between policies means.",
        "- **Data contract:** records are `{id, image, depth, mask}` — a PIL image (or a path to one) with sides 14..4,096 px and aspect ratio at most 4.0, a float H × W array of metric depth in metres (or a path to a `.npy`), an optional boolean H × W validity mask (missing means `depth > 0`) covering at least 5 % of the pixels, depth at most 1,000 m, ids matching `[A-Za-z0-9_.:-]{1,64}` and unique; a training set needs 4..2,000 records; images are de-duplicated by decoded-pixel digest and split by `scan` / `group` so views of one scene never straddle splits. Only reference pixels inside 0.6..350 m are scored. BYOD accepts a `.zip` or a directory (upload dialog on Colab, or `BYOD_PATH` on any runtime) holding `records.csv` and the files, and requires a non-empty `group` on every row — the notebook's automatic split is group-disjoint only because the loader refuses ungrouped rows (`load_byod_dataset(..., require_group=False)` is the explicit opt-out, without that guarantee). The seeded group split keeps about 20 % of the groups for test and 15 % for validation, at least one each, so a BYOD set needs at least **4 distinct groups**, and the training groups must hold at least 4 views; Section 4 checks both before any model runs and names the split it refuses.",
        "- **Validation is structural, not semantic:** nothing checks that a depth map belongs to its image or that its unit is metres beyond the 1,000 m ceiling — a mis-paired or mis-scaled set is trained on without complaint.",
        "- **Privacy:** Do not upload confidential or restricted data to a hosted runtime unless you are authorized to process it there — RGB-D captures of homes, workplaces or people are exactly that. The default path uploads nothing.",
        "- **External access (data):** besides the Hub snapshot, the default path fetches 120 pinned objects — for each of 40 DIODE views the RGB PNG, the `_depth.npy` and the `_depth_mask.npy`, 312,448,846 bytes in total, one SHA-256 each in the carried `SAMPLE_RECORDS` table — by HTTPS Range requests at pinned byte offsets (`ARCHIVE_MEMBERS`) of `share.phys.ethz.ch/~pf/bingkedata/marigold/evaluation_dataset/diode/diode_val.tar` (6,400,440,320 bytes, uncompressed; a reply that is not `206 Partial Content` with the pinned `Content-Range` is refused), each refused on any byte-size or SHA-256 mismatch before it is decoded; the files are DIODE's own (CC BY 4.0, Vasiljevic et al. 2019) as served by the Marigold evaluation dataset archive at ETH Zürich PRS. (Until 2026-10 the same files, with identical digests, came from a Hugging Face Hub mirror that has since been withdrawn.)",
    ],
    "cells": [
        {
            "md": (
                "## 4. Referenced corpus, validation and scan-level split\n\n"
                "`fetch_corpus` downloads the 120 pinned files (or reads them from the cache), refuses a byte-size or "
                "SHA-256 mismatch per file before it is decoded, and `read_corpus` turns each view into a `{{id, image, "
                "depth, mask}}` record with its domain, scene, scan and source URL. `build_sample_dataset` draws whole "
                "scans per domain — 6 training, 2 validation and 2 test scans from each of the indoor and outdoor sets — "
                "by a seeded shuffle, so the 24 / 8 / 8 views never share a scene across splits; `validate_dataset` then "
                "checks every record against the contract, `check_split_disjoint` asserts no view (by decoded-pixel "
                "digest) and no scan appears in two splits, `scan_summary` reports scans and domains per split, and the "
                "training records table is written to `outputs/{stem}_train.csv` in the shape BYOD expects.\n\n"
                "Look for: 40 views, 20 scans of 2, splits 24 / 8 / 8 with 12 / 4 / 4 scans, three digests, median "
                "depths from about a metre indoors to tens of metres outdoors, and four refusal probes — a duplicate id, "
                "a depth map of the wrong shape, a mask with no valid pixels and a dataset too small to train on — each "
                "rejected before `torch` does anything. Allow about ten minutes on the first run for the 312 MB download from "
                "the ETH archive: on a Colab T4 on 2026-10-03 the workshop notebook's prepare step, which fetches these same "
                "120 files, took 629.8 s of an 823 s run (the whole run took 402.8 s when the files came from the former Hub "
                "mirror).\n\n"
                "**Bring your own data (optional).** With `USE_BYOD = True` the cell reads your set from `BYOD_PATH` (a `.zip` "
                "or a directory) or, when that is empty, from the Colab upload dialog. Before any model runs it checks that "
                "the set has at least 4 distinct groups (the seeded split keeps one or more for test, one or more for "
                "validation and the rest for training), that no split comes out empty and that training keeps at least 4 "
                "views, and it names the split it refuses. An empty or cancelled upload asks you to choose a file or set "
                "`BYOD_PATH`.\n\n"
                "**Predict before running:** if the 40 views came from 20 scans and the split is by whole scan, can the "
                "test split contain a view whose twin (the other view of its scan) is in training? Which of the four "
                "refusal probes do you expect the validator to accept?"
            ),
            "code": (
                "import hashlib\n"
                "import io\n"
                "import json\n"
                "import time\n\n"
                'USE_BYOD = False  # @param {{type:"boolean"}}\n'
                'BYOD_PATH = ""  # @param {{type:"string"}}\n'
                'SPLIT_SEED = 42  # @param {{type:"integer"}}\n\n'
                "MIN_BYOD_GROUPS = 4  # one or more groups each for test and validation, at least two for training\n\n"
                "def byod_split(records, seed):\n"
                "    \"\"\"split_dataset with the group count checked first and every split named in a refusal.\"\"\"\n"
                "    groups = sorted({{str(r.get('scan') or r.get('group') or r['id']) for r in records}})\n"
                "    if len(groups) < MIN_BYOD_GROUPS:\n"
                "        raise ValueError(f'BYOD set has {{len(groups)}} distinct group(s) ({{len(records)}} records); the group-disjoint split needs at least {{MIN_BYOD_GROUPS}} (one or more each for test and validation, at least two for training). Add views from more scans, sessions or devices, and give each its own `group` value.')\n"
                "    parts = split_dataset(records, seed=seed)\n"
                "    for name, part in parts.items():\n"
                "        if not part:\n"
                "            raise ValueError(f'the {{name}} split of the BYOD set is empty ({{len(groups)}} groups); add views from more groups')\n"
                "    return parts\n\n"
                "os.makedirs('outputs', exist_ok=True)\n"
                "t0 = time.perf_counter()\n"
                "if USE_BYOD:\n"
                "    if BYOD_PATH.strip():\n"
                "        byod_path = Path(BYOD_PATH.strip()).expanduser()\n"
                "        if not byod_path.exists():\n"
                "            raise FileNotFoundError(f'BYOD_PATH {{str(byod_path)!r}} does not exist; set it to a .zip or a directory holding records.csv')\n"
                "        file_name = byod_path.name\n"
                "    else:\n"
                "        from google.colab import files\n"
                "        uploaded = files.upload()\n"
                "        if len(uploaded) != 1:\n"
                "            raise ValueError(f'Upload exactly one .zip file (received {{len(uploaded)}}): run this cell again and choose the file, or set BYOD_PATH to a .zip or a directory.')\n"
                "        file_name, payload = next(iter(uploaded.items()))\n"
                "        byod_path = Path('work') / file_name\n"
                "        byod_path.parent.mkdir(parents=True, exist_ok=True)\n"
                "        byod_path.write_bytes(payload)\n"
                "    records = load_byod_dataset(byod_path)\n"
                "    splits = byod_split(records, SPLIT_SEED)\n"
                "    data_source = 'BYOD (' + file_name + ')'\n"
                "    raw_count = {{'byod': len(records)}}\n"
                "else:\n"
                "    corpus = read_corpus(fetch_corpus(cache_dir='weights/diode-sample'))\n"
                "    raw_count = {{'views': len(corpus), 'scans': len({{(r['domain'], r['scan']) for r in corpus}}), 'domains': sorted({{r['domain'] for r in corpus}})}}\n"
                "    splits = build_sample_dataset(corpus, seed=SPLIT_SEED)\n"
                "    data_source = f'{{CORPUS_NAME}} ({{CORPUS_RELEASE}}; {{CORPUS_LICENSE}})'\n"
                "fetch_seconds = round(time.perf_counter() - t0, 1)\n"
                "train_records, val_records, test_records = splits['train'], splits['validation'], splits['test']\n"
                "dataset_manifests = {{name: validate_dataset(part, min_records=1) for name, part in splits.items()}}\n"
                "disjoint = check_split_disjoint(splits)\n"
                "summary = scan_summary(splits)\n"
                "write_dataset_csv(train_records, 'outputs/{stem}_train.csv')\n"
                "print({{'data_source': data_source, 'raw': raw_count, 'splits': disjoint, 'scan_summary': summary, 'fetch_seconds': fetch_seconds, 'corpus_bytes': CORPUS_BYTES}})\n"
                "for name, manifest in dataset_manifests.items():\n"
                "    print({{name: {{'n': manifest['n_records'], 'scans': manifest['scans'], 'domains': manifest['domain_counts'], 'image_side': manifest['image_side'], 'valid_fraction': manifest['valid_fraction'], 'median_depth_m': manifest['median_depth_m'], 'digest': manifest['digest'][:16] + '...'}}}})\n"
                "example = train_records[0]\n"
                "print({{'example': {{k: example[k] for k in ('id', 'domain', 'scene', 'scan', 'source_url') if k in example}}, 'size': example['image'].size, 'depth_dtype': str(example['depth'].dtype), 'valid_fraction': round(float(example['mask'].mean()), 4)}})\n\n"
                "probes = {{\n"
                "    'duplicate id': [{{**r, 'id': 'same'}} for r in train_records[:4]],\n"
                "    'depth shape': [{{**train_records[0], 'depth': train_records[0]['depth'][:-1]}}, *train_records[1:4]],\n"
                "    'no valid depth': [{{**train_records[0], 'mask': np.zeros_like(train_records[0]['mask'])}}, *train_records[1:4]],\n"
                "    'too small': train_records[:3],\n"
                "}}\n"
                "for name, probe in probes.items():\n"
                "    try:\n"
                "        validate_dataset(probe)\n"
                "        print({{'probe': name, 'verdict': 'accepted'}})\n"
                "    except (TypeError, ValueError) as exc:\n"
                "        print({{'probe': name, 'rejected': str(exc)[:110]}})"
            ),
        },
        {
            "md": (
                "**What to notice:** 24 / 8 / 8 views from 12 / 4 / 4 scans, three different digests, and all four refusal "
                "probes rejected.\n\n"
                "<details><summary>Check your reasoning</summary>No: the split draws whole scans, so both views of a scan "
                "land in the same split, and `check_split_disjoint` would raise if a view or a scan appeared in two splits. "
                "That matters because the two views of one scan are nearly the same scene; a twin in training would make "
                "the test score optimistic. None of the probes is accepted: in the recorded Colab T4 run (2026-10-03) the "
                "duplicate id, the depth map one row short, the empty mask and the three-record set were each rejected by "
                "`validate_dataset` before `torch` ran.</details>\n\n"
                "## 5. Predict through the inference contract, with a metric reference\n\n"
                "Before any adaptation, the inference contract is exercised as it always was, on one test view. "
                "`validate_inputs` applies exactly the checks `predict` applies — type, sides 14..`MAX_IMAGE_SIDE` px, "
                "aspect ratio at most `MAX_ASPECT_RATIO` — and returns an input manifest; a deliberately over-wide image "
                "is validated too and its rejection recorded as a finding. `predict` returns relative inverse depth at "
                "the input resolution with four sanity checks. Because this view carries metric depth from a laser "
                "scanner, `evaluation_report` can for the first time return **`sample-sanity`**: it aligns the "
                "prediction to the reference by least squares in inverse depth (the pipeline's own `abs_rel`, invalid "
                "pixels zeroed out of the reference) and reports AbsRel for this one image — sanity evidence, not a "
                "benchmark. The build record's probe view — an outdoor scan — scored 0.12; indoor views scored 0.04–0.13 "
                "and outdoor views with sky and distant structure up to 0.40. A side-by-side preview (image | predicted inverse depth) is displayed.\n\n"
                "**Every pass starts from the pretrained model.** Section 7 changes the model in memory. If this cell, "
                "Section 6 or Section 7 runs again after Section 7 (a BYOD run or one of the optional experiments), it "
                "first reloads the pretrained model from the verified snapshot with `reset_to_pretrained()`, so a "
                "*zero-shot* or *before* number is never read from the adapted model.\n\n"
                "**Predict before running:** in the preview, will the bottom of the image be brighter (nearer) or darker "
                "than the top? Will the aligned AbsRel of this one outdoor view be nearer 0.01, 0.1 or 1?"
            ),
            "code": (
                "import gc\n\n"
                "def reset_to_pretrained():\n"
                "    \"\"\"Sections 5-7 start from the pretrained model: if an earlier pass adapted `pipe`, reload it from the verified snapshot.\"\"\"\n"
                "    global pipe\n"
                "    if pipe.adapter is None:\n"
                "        return\n"
                "    pipe = None\n"
                "    gc.collect()\n"
                "    if torch.cuda.is_available():\n"
                "        torch.cuda.empty_cache()\n"
                "    pipe = DepthAnythingPipeline.from_pretrained(weights_dir=WEIGHTS_DIR)\n"
                "    print({{'reloaded': 'the pretrained model, from the verified snapshot', 'reason': 'an earlier pass had adapted the model in memory'}})\n\n"
                "reset_to_pretrained()\n"
                "probe_record = test_records[0]\n"
                "image = probe_record['image']\n"
                "print({{'ceilings': {{'MIN_IMAGE_SIDE': MIN_IMAGE_SIDE, 'MAX_IMAGE_SIDE': MAX_IMAGE_SIDE, 'MAX_ASPECT_RATIO': MAX_ASPECT_RATIO}}, 'contract': {{'DEPTH_KIND': DEPTH_KIND, 'TRANSFORMER_BLOCKS': TRANSFORMER_BLOCKS, 'PARAMETER_COUNT': PARAMETER_COUNT, 'EVAL_DEPTH_RANGE_M': EVAL_DEPTH_RANGE_M}}}})\n"
                "input_manifest = validate_inputs(image, names=[probe_record['id']])\n"
                "try:\n"
                "    validate_inputs(Image.new('RGB', (MIN_IMAGE_SIDE, int(MIN_IMAGE_SIDE * (MAX_ASPECT_RATIO + 1)))))\n"
                "except ValueError as exc:\n"
                "    input_manifest['findings'].append({{'input': 'over-wide-probe', 'verdict': 'rejected', 'message': str(exc)}})\n"
                "with open('outputs/{stem}_input_manifest.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(input_manifest, handle, indent=2, ensure_ascii=False)\n"
                "started = time.perf_counter()\n"
                "result = pipe.predict(image)\n"
                "predict_seconds = round(time.perf_counter() - started, 3)\n"
                "depth = result['depth']\n"
                "checks = {{\n"
                "    'shape_matches_input': depth.shape == (result['height'], result['width']) == (image.height, image.width),\n"
                "    'dtype_float32': depth.dtype == np.float32,\n"
                "    'all_finite': bool(np.isfinite(depth).all()),\n"
                "    'non_degenerate_range': result['depth_max'] > result['depth_min'],\n"
                "}}\n"
                "if not all(checks.values()):\n"
                "    raise RuntimeError(f'depth map failed a sanity check: {{checks}}')\n"
                "reference_depth = np.where(probe_record['mask'], probe_record['depth'], 0.0)\n"
                "report = evaluation_report(result, reference_depth, sample_kind=f\"DIODE {{probe_record.get('domain', '')}} view {{probe_record['id']}}\" if not USE_BYOD else 'BYOD test view')\n"
                "print({{'probe_id': probe_record['id'], 'domain': probe_record.get('domain'), 'seconds': predict_seconds, 'device': pipe.device, 'checks': checks, 'findings': len(input_manifest['findings'])}})\n"
                "print({{'verdict': report['verdict'], 'metrics': report['metrics'], 'reason': report['reason']}})\n"
                "assert report['verdict'] == 'sample-sanity' and report['metrics'][0]['id'] == 'abs_rel'\n\n"
                "def preview(image, maps):\n"
                "    tiles = [image.convert('RGB')]\n"
                "    for m in maps:\n"
                "        lo, hi = float(m.min()), float(m.max())\n"
                "        tiles.append(Image.fromarray(np.round((m - lo) / (hi - lo + 1e-9) * 255.0).astype(np.uint8)).convert('RGB'))\n"
                "    canvas = Image.new('RGB', (image.width * len(tiles), image.height))\n"
                "    for i, tile in enumerate(tiles):\n"
                "        canvas.paste(tile, (image.width * i, 0))\n"
                "    return canvas\n\n"
                "try:\n"
                "    show_image = display  # provided by the isolated worker (and by IPython); IPython is not installed in the isolated environment\n"
                "except NameError:\n"
                "    show_image = None\n"
                "if show_image is not None:\n"
                "    show_image(preview(image, [depth]).reduce(2))\n"
                "else:\n"
                "    print({{'preview': 'display unavailable; the preview PNG is written in Section 9'}})"
            ),
        },
        {
            "md": (
                "**What to notice:** four sanity checks `True`, verdict `sample-sanity`, and the brightness gradient of the "
                "preview.\n\n"
                "<details><summary>Check your reasoning</summary>Brighter at the bottom: the map is inverse depth, larger "
                "= nearer, and the ground in front of the camera is nearest. The aligned AbsRel of the probe view "
                "`test-000` (outdoor) was 0.1212 over 703,835 reference pixels in the recorded Colab T4 run (2026-10-03), "
                "so near 0.1: after the best scale and shift, the prediction is on average about 12 % away from the laser "
                "depth. That is one image — sanity evidence that the contract and the metric work, not a benchmark.</details>\n\n"
                "## 6. The two priors and the zero-shot policy\n\n"
                "Three numbers frame the adaptation, all on the 8 test views. The **constant prior** puts every pixel at "
                "the image's own median reference depth — an oracle constant, the strongest flat guess. The "
                "**vertical-gradient prior** predicts inverse depth rising from the top row to the bottom row and is "
                "aligned exactly like a model prediction: what \"the ground is nearer\" alone buys. The **zero-shot "
                "policy** is `pipe.evaluate` on the untouched checkpoint: mean AbsRel and δ1 over views, per domain and "
                "per view. Read the per-domain split: outdoor DIODE views with sky, foliage and 100 m ranges are where a "
                "relative-depth model struggles. Two zero-shot depth maps are kept for the before/after comparison in "
                "Section 9. The cell reloads the pretrained model first if an earlier pass adapted it, and refuses to report "
                "an adapted model as zero-shot. Scoring the 8 test views took 3.2 s in the local Windows CPU pre-flight of "
                "2026-09-19.\n\n"
                "**Predict before running:** order the three — constant prior, vertical-gradient prior, zero-shot "
                "checkpoint — from best (lowest AbsRel) to worst. Will the checkpoint do better indoors or outdoors?"
            ),
            "code": (
                "def brief(m):\n"
                "    return {{'abs_rel': round(m['abs_rel'], 4), 'delta1': round(m['delta1'], 4), 'n': m['n']}}\n\n"
                "reset_to_pretrained()\n"
                "priors = prior_baselines(test_records)\n"
                "print({{'constant_prior': brief(priors['constant_prior']), 'baseline': priors['constant_prior']['baseline']}})\n"
                "print({{'vertical_gradient_prior': brief(priors['vertical_gradient_prior']), 'baseline': priors['vertical_gradient_prior']['baseline']}})\n"
                "t0 = time.perf_counter()\n"
                "zero_shot_test = pipe.evaluate(test_records)\n"
                "if zero_shot_test['adapted']:\n"
                "    raise RuntimeError('Section 6 must score the untouched checkpoint, but the model in memory is adapted. Restart the session and choose Run all.')\n"
                "print({{'zero_shot_policy': zero_shot_test['policy'], 'adapted': zero_shot_test['adapted'], 'test': brief(zero_shot_test), 'per_domain': {{d: {{'abs_rel': round(v['abs_rel'], 4), 'delta1': round(v['delta1'], 4), 'n': v['n']}} for d, v in zero_shot_test['per_domain'].items()}}, 'verdict': zero_shot_test['verdict'], 'seconds': round(time.perf_counter() - t0, 1)}})\n"
                "print({{'per_view': [(r['id'], r['domain'], round(r['abs_rel'], 3), round(r['delta1'], 3)) for r in zero_shot_test['per_image']]}})\n"
                "print({{'definitions': zero_shot_test['definitions']}})\n"
                "show = test_records[:2]\n"
                "zero_shot_maps = {{r['id']: pipe.predict(r['image'])['depth'] for r in show}}\n"
                "assert zero_shot_test['abs_rel'] < priors['constant_prior']['abs_rel'] and zero_shot_test['abs_rel'] < priors['vertical_gradient_prior']['abs_rel']"
            ),
        },
        {
            "md": (
                "**What to notice:** the order of the three rows, `adapted: False`, and the indoor / outdoor gap.\n\n"
                "<details><summary>Check your reasoning</summary>Checkpoint best, then the gradient prior, then the "
                "constant prior: in the recorded Colab T4 run (2026-10-03) the test AbsRel was 0.1800 for the checkpoint, "
                "0.2597 for the vertical-gradient prior and 0.3346 for the constant prior. The gradient prior beats the "
                "constant one because \"the ground is nearer\" is true of most photographs; the checkpoint beats both "
                "because it reads the scene. Indoors is far easier (0.075 against 0.285 outdoors): indoor ranges are a few "
                "metres with walls and floors, while outdoor views have sky, foliage and distances up to 350 m.</details>\n\n"
                "## 7. The policy ladder: neck and head, then a bounded unfreeze, selected against the checkpoint\n\n"
                "`pipe.adapt` scores the untouched checkpoint on the validation views first (epoch 0, the zero-shot "
                "policy), then trains the DPT neck and head — 2,728,513 parameters — on the frozen backbone for "
                "`HEAD_EPOCHS` epochs (the frozen policy), then unfreezes the last `TRAINABLE_BLOCKS` transformer blocks "
                "— two by default, 3,550,464 of 24,785,089 parameters; the patch embedding, the position embedding, the "
                "earlier blocks and the final norm stay frozen — and trains them with the neck and head for `EPOCHS` more "
                "epochs (the unfrozen policy). Every epoch trains one view at a time with AdamW at `LEARNING_RATE` "
                "(weight decay 0.01, gradient clipping 1.0, seeded order, no augmentation) under a scale-and-shift-"
                "invariant squared error on inverse depth — the prediction is affinely aligned to the reference in closed "
                "form before the residual is taken, because the model's scale and shift are free — and is scored on "
                "validation by `evaluate`. The epoch with the **lowest validation AbsRel** is kept and its tensors "
                "restored, so the selected policy can be the checkpoint itself.\n\n"
                "The validation views are four scans — one view is an eighth of the number. The cell prints one line "
                "per epoch with the elapsed time, and before it starts it prints a rough per-epoch time estimate from this "
                "runtime's Section 6 scoring speed (an estimate, not a measurement).\n\n"
                "**Adaptation always starts from the pretrained model.** If this cell runs again (for example with "
                "`LEARNING_RATE = 3e-5` in Section 10), it first reloads the pretrained model from the verified snapshot, "
                "so the new ladder never stacks on the previous one, epoch 0 really is the untouched checkpoint, and the "
                "exported adapter holds exactly what this run trained; the cell refuses to run `pipe.adapt` on a model that "
                "is already adapted.\n\n"
                "**Predict before running:** will validation AbsRel fall at every epoch? Which policy will be kept — the "
                "checkpoint (epoch 0), the neck and head (epochs 1–2) or the unfreeze (epochs 3–5)?"
            ),
            "code": (
                'HEAD_EPOCHS = 2  # @param {{type:"integer"}}\n'
                'EPOCHS = 3  # @param {{type:"integer"}}\n'
                'LEARNING_RATE = 1e-5  # @param {{type:"number"}}\n'
                'TRAINABLE_BLOCKS = 2  # @param {{type:"integer"}}\n\n'
                "def report_epoch(entry):\n"
                "    row = {{'epoch': entry['epoch'], 'stage': entry['stage'], 'train_loss': round(entry['train_loss'], 4) if entry['train_loss'] is not None else None}}\n"
                "    if entry.get('val'):\n"
                "        row['val_abs_rel'] = round(entry['val']['abs_rel'], 4)\n"
                "        row['val_delta1'] = round(entry['val']['delta1'], 4)\n"
                "    row['elapsed_s'] = round(time.perf_counter() - t0, 1)\n"
                "    print(row)\n\n"
                "reset_to_pretrained()\n"
                "if pipe.adapter is not None:\n"
                "    raise RuntimeError('pipe.adapt would train on top of an earlier adaptation; restart the session and choose Run all.')\n"
                "per_view = zero_shot_test['seconds'] / max(1, zero_shot_test['n'])\n"
                "n_epochs = HEAD_EPOCHS + (EPOCHS if TRAINABLE_BLOCKS > 0 else 0)\n"
                "print({{'epochs': n_epochs, 'training_views_per_epoch': len(train_records), 'validation_views_per_epoch': len(val_records), 'rough_seconds_per_epoch': round(per_view * (3 * len(train_records) + len(val_records))), 'estimate': 'from Section 6 scoring speed on this runtime; a training step is assumed to cost about three predictions'}})\n"
                "t0 = time.perf_counter()\n"
                "adapt_result = pipe.adapt(train_records, val_records, trainable_blocks=TRAINABLE_BLOCKS, head_epochs=HEAD_EPOCHS, epochs=EPOCHS, lr=LEARNING_RATE, progress=report_epoch)\n"
                "adapt_seconds = round(time.perf_counter() - t0, 1)\n"
                "report_epoch(adapt_result['history'][0])\n"
                "print({{'selected_policy': adapt_result['policy'], 'best_epoch': adapt_result['best_epoch'], 'selection': adapt_result['selection'], 'trainable_neck_head': adapt_result['n_trainable_head'], 'trainable_blocks': adapt_result['n_trainable_blocks'], 'total_parameters': adapt_result['n_total'], 'seconds': adapt_seconds}})"
            ),
        },
        {
            "md": (
                "**What to notice:** epoch 0 is labelled `zero-shot (no adaptation)` and its validation AbsRel is the "
                "untouched checkpoint's; the kept epoch is the one with the lowest validation AbsRel.\n\n"
                "<details><summary>Check your reasoning</summary>At the defaults, yes, it fell at every epoch: in the "
                "recorded Colab T4 run (2026-10-03) validation AbsRel went 0.2426 (epoch 0, the checkpoint) → 0.2201 → "
                "0.1937 (neck and head) → 0.1394 → 0.1328 → 0.1295 (unfrozen), so the unfreeze at epoch 5 was kept. It "
                "need not fall: at a higher learning rate it can turn, and the rule then keeps an earlier epoch — epoch 0 "
                "means \"do not adapt\". Choosing the epoch on the test split would make Section 8 optimistic, because the "
                "test views would have helped pick the model they then judge.</details>\n\n"
                "## 8. Held-out evaluation\n\n"
                "The test split was never used for training or policy selection, and no scan in it appears in the "
                "training or validation splits. The selected model is scored exactly as the checkpoint was in Section 6, "
                "and the four rows are put side by side: constant prior, vertical-gradient prior, zero-shot policy, "
                "selected policy — with per-domain and per-view AbsRel. Read the policy first: if validation kept "
                "epoch 0, the last two rows are the same model; otherwise the delta is what the adaptation bought on "
                "8 views. The cell then prints a **run summary** computed from *your* run — the selected policy, the AbsRel "
                "and δ1 change against the checkpoint, and how many test views improved, worsened or stayed the same — and "
                "keeps a **run history** for this session, one row per pass through Section 8, so an experiment can be "
                "compared with the default run (Section 10). The cell asserts the selected model beats both priors; it "
                "does **not** assert a gain over the checkpoint, because that is the question, not the answer. Eight views "
                "from four scans of one seeded split give no dispersion estimate.\n\n"
                "**Predict before running:** will the selected model beat the checkpoint on the held-out views, and by "
                "more or less than 0.05 AbsRel? Will every one of the 8 test views improve?"
            ),
            "code": (
                "adapted_test = pipe.evaluate(test_records)\n"
                "adapted_val = pipe.evaluate(val_records)\n"
                "comparison = {{\n"
                "    metric: {{'constant_prior': round(priors['constant_prior'][metric], 4), 'vertical_gradient_prior': round(priors['vertical_gradient_prior'][metric], 4), 'zero_shot': round(zero_shot_test[metric], 4), 'selected_policy': round(adapted_test[metric], 4)}}\n"
                "    for metric in ('abs_rel', 'delta1')\n"
                "}}\n"
                "comparison['per_domain_abs_rel'] = {{d: {{'zero_shot': round(zero_shot_test['per_domain'][d]['abs_rel'], 4), 'selected': round(v['abs_rel'], 4)}} for d, v in adapted_test['per_domain'].items()}}\n"
                "comparison['per_view_abs_rel'] = {{z['id']: {{'zero_shot': round(z['abs_rel'], 4), 'selected': round(a['abs_rel'], 4)}} for z, a in zip(zero_shot_test['per_image'], adapted_test['per_image'])}}\n"
                "comparison['delta_vs_zero_shot'] = {{metric: round(adapted_test[metric] - zero_shot_test[metric], 4) for metric in ('abs_rel', 'delta1')}}\n"
                "comparison['selected_policy'] = adapt_result['policy']\n"
                "for metric, row in comparison.items():\n"
                "    print({{metric: row}})\n"
                "view_change = [round(a['abs_rel'], 4) - round(z['abs_rel'], 4) for z, a in zip(zero_shot_test['per_image'], adapted_test['per_image'])]\n"
                "run_summary = {{\n"
                "    'data': 'BYOD' if USE_BYOD else 'DIODE sample',\n"
                "    'selected_policy': adapt_result['policy'],\n"
                "    'best_epoch': adapt_result['best_epoch'],\n"
                "    'abs_rel_zero_shot_to_selected': [round(zero_shot_test['abs_rel'], 4), round(adapted_test['abs_rel'], 4)],\n"
                "    'delta_abs_rel': comparison['delta_vs_zero_shot']['abs_rel'],\n"
                "    'delta_delta1': comparison['delta_vs_zero_shot']['delta1'],\n"
                "    'test_views_improved': sum(d < 0 for d in view_change),\n"
                "    'test_views_worsened': sum(d > 0 for d in view_change),\n"
                "    'test_views_unchanged': sum(d == 0 for d in view_change),\n"
                "}}\n"
                "print({{'run_summary': run_summary}})\n"
                "run_history = globals().get('run_history', [])\n"
                "run_history.append({{'run': len(run_history) + 1, 'data': run_summary['data'], 'head_epochs': HEAD_EPOCHS, 'epochs': EPOCHS, 'learning_rate': LEARNING_RATE, 'trainable_blocks': TRAINABLE_BLOCKS, 'best_epoch': adapt_result['best_epoch'], 'val_abs_rel_epoch0': round(adapt_result['history'][0]['val']['abs_rel'], 4) if adapt_result['history'][0]['val'] else None, 'zero_shot': run_summary['abs_rel_zero_shot_to_selected'][0], 'selected': run_summary['abs_rel_zero_shot_to_selected'][1], 'delta': run_summary['delta_abs_rel'], 'improved': run_summary['test_views_improved'], 'worsened': run_summary['test_views_worsened']}})\n"
                "for h in run_history:\n"
                "    print(h)\n"
                "evaluation_report_payload = {{\n"
                "    'model': {{'id': MODEL_ID, 'revision': MODEL_REVISION, 'key': MODEL_KEY}},\n"
                "    'data_source': data_source,\n"
                "    'dataset_digests': {{name: manifest['digest'] for name, manifest in dataset_manifests.items()}},\n"
                "    'splits': disjoint,\n"
                "    'scan_summary': summary,\n"
                "    'single_view_report': report,\n"
                "    'priors': {{k: {{kk: vv for kk, vv in v.items() if kk != 'per_image'}} for k, v in priors.items()}},\n"
                "    'zero_shot_test': zero_shot_test,\n"
                "    'validation_metrics': adapted_val,\n"
                "    'test_metrics': adapted_test,\n"
                "    'comparison': comparison,\n"
                "    'run_summary': run_summary,\n"
                "    'adaptation': {{k: v for k, v in adapt_result.items() if k not in ('history', 'trainable_names')}},\n"
                "    'history': adapt_result['history'],\n"
                "    'adaptation_seconds': adapt_seconds,\n"
                "}}\n"
                "with open('outputs/{stem}_evaluation_report.json', 'w', encoding='utf-8') as f:\n"
                "    json.dump(evaluation_report_payload, f, indent=2, ensure_ascii=False)\n"
                "assert adapted_test['abs_rel'] < priors['constant_prior']['abs_rel'] and adapted_test['abs_rel'] < priors['vertical_gradient_prior']['abs_rel']\n"
                "print({{'report': 'outputs/{stem}_evaluation_report.json'}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the run summary — the selected policy, the AbsRel change and the improved / worsened "
                "view counts — and the per-domain rows.\n\n"
                "<details><summary>Check your reasoning</summary>In the recorded Colab T4 run (2026-10-03) the selected "
                "unfreeze lowered held-out AbsRel from 0.1800 to 0.1669 (Δ −0.0131; δ1 0.7644 → 0.7652), much less than "
                "0.05, almost all of it outdoors (0.285 → 0.2634; indoors 0.075 → 0.0705). Not every view improved: a local "
                "CPU run of the same defaults (2026-10-03) counted 5 of the 8 test views better and 3 worse. A mean gain "
                "that hides worse views is common with 24 training views; with 8 test views from 4 scans and no dispersion "
                "estimate, a difference of 0.013 is within the grain of the split.</details>\n\n"
                "## 9. Depth maps before and after, export the adapter and reload it\n\n"
                "Two test views are predicted by the selected model and rendered beside the zero-shot maps kept in "
                "Section 6 (image | zero-shot | selected, normalised per map, brighter = nearer) with each map's aligned "
                "AbsRel; `outputs/{stem}_preview.png` holds the render. A relative-depth map is a per-image ordering, so "
                "read the pair for structure — where the selected model places the ground plane, the walls, the far "
                "field — not for absolute brightness.\n\n"
                "`pipe.save_artifact` writes the DPT neck and head tensors and, when the unfrozen policy was selected, "
                "the trained block tensors — 10.9 MB for neck and head, 25.1 MB with two blocks — as "
                "`adapter.safetensors`, with a `manifest.json` recording the artifact format, the base model id and "
                "revision, the digest of the base `model.safetensors`, the selected policy, the tensor names, the file "
                "size and SHA-256, the training configuration and the epoch history (OUT8). "
                "`DepthAnythingPipeline.from_artifact` re-verifies the base snapshot, checks the artifact manifest and "
                "digest **before** deserialising, refuses any tensor that is not a neck, head or transformer-block tensor "
                "of the base, and overlays the tensors onto a freshly loaded base — a new object from files, not the "
                "in-memory model (VER2). The cell asserts an identical depth map on a test view and an identical test "
                "AbsRel (VER4), and ends by printing the run summary of Section 8 again, so the last output of the notebook "
                "states what *your* run selected and what it changed.\n\n"
                "**Predict before running:** if validation had kept epoch 0 (the checkpoint), what would the adapter "
                "contain, and would the before and after maps differ?"
            ),
            "code": (
                "import shutil\n\n"
                "rows = []\n"
                "canvases = []\n"
                "for record in show:\n"
                "    after = pipe.predict(record['image'])['depth']\n"
                "    before = zero_shot_maps[record['id']]\n"
                "    rows.append({{'id': record['id'], 'domain': record.get('domain', ''), 'zero_shot_abs_rel': round(aligned_abs_rel(before, record['depth'], record['mask']), 4), 'selected_abs_rel': round(aligned_abs_rel(after, record['depth'], record['mask']), 4), 'source_url': record.get('source_url', '')}})\n"
                "    print(rows[-1])\n"
                "    canvases.append(preview(record['image'], [before, after]))\n"
                "sheet = Image.new('RGB', (max(c.width for c in canvases), sum(c.height for c in canvases)))\n"
                "y = 0\n"
                "for c in canvases:\n"
                "    sheet.paste(c, (0, y))\n"
                "    y += c.height\n"
                "sheet.save('outputs/{stem}_preview.png')\n"
                "if show_image is not None:\n"
                "    show_image(sheet.reduce(3))\n\n"
                "artifact_dir = Path('outputs/{stem}_adapter')\n"
                "shutil.rmtree(artifact_dir, ignore_errors=True)\n"
                "pipe.save_artifact(artifact_dir, metadata={{'tutorial': '{stem}', 'data_source': data_source}})\n"
                "artifact_manifest = json.loads((artifact_dir / 'manifest.json').read_text(encoding='utf-8'))\n"
                "print({{'artifact': str(artifact_dir), 'format': artifact_manifest['format'], 'policy': artifact_manifest['adapter']['policy'], 'tensors': len(artifact_manifest['tensors']), 'bytes': artifact_manifest['files'][0]['bytes'], 'sha256': artifact_manifest['files'][0]['sha256'][:16] + '...'}})\n\n"
                "reloaded = DepthAnythingPipeline.from_artifact(artifact_dir, weights_dir=WEIGHTS_DIR, device=pipe.device)\n"
                "reloaded_map = reloaded.predict(show[0]['image'])['depth']\n"
                "reloaded_test = reloaded.evaluate(test_records)\n"
                "parity = {{'depth_map_identical': bool(np.array_equal(reloaded_map, pipe.predict(show[0]['image'])['depth'])), 'abs_rel_in_memory': round(adapted_test['abs_rel'], 6), 'abs_rel_reloaded': round(reloaded_test['abs_rel'], 6)}}\n"
                "print({{'reload_parity': parity, 'reloaded_policy': reloaded.adapter['policy'], 'reloaded_best_epoch': reloaded.adapter['best_epoch']}})\n"
                "assert parity['depth_map_identical'] and abs(adapted_test['abs_rel'] - reloaded_test['abs_rel']) < 1e-9\n\n"
                "weight_entry = next(entry for entry in MANIFEST['files'] if entry['path'] == WEIGHTS_FILE)\n"
                "result_payload = {{\n"
                "    'notebook_source': NOTEBOOK_SOURCE,\n"
                "    'repository_revision': NOTEBOOK_SOURCE['repository_revision'],\n"
                "    'model_id': MODEL_ID,\n"
                "    'model_revision': MODEL_REVISION,\n"
                "    'model_license': MODEL_LICENSE,\n"
                "    'snapshot': {{'path': str(WEIGHTS_DIR), 'files': snapshot['files'], 'total_bytes': snapshot.get('total_bytes'), 'fetched_this_run': fetched, 'weight_file': WEIGHTS_FILE, 'weight_format': 'safetensors, digest-verified', 'weight_sha256': weight_entry['sha256']}},\n"
                "    'data_source': data_source,\n"
                "    'corpus': {{'name': CORPUS_NAME, 'release': CORPUS_RELEASE, 'url': CORPUS_URL, 'archive_bytes': CORPUS_ARCHIVE_BYTES, 'views': len(SAMPLE_RECORDS), 'bytes': CORPUS_BYTES, 'license': CORPUS_LICENSE}},\n"
                "    'inference_contract': {{'input_manifest': input_manifest, 'sanity_checks': checks, 'probe_id': probe_record['id'], 'single_view_report': report, 'seconds': predict_seconds}},\n"
                "    'comparison': comparison,\n"
                "    'run_summary': run_summary,\n"
                "    'before_after': rows,\n"
                "    'preview_file': 'outputs/{stem}_preview.png',\n"
                "    'artifact': {{'dir': str(artifact_dir), 'sha256': artifact_manifest['files'][0]['sha256'], 'bytes': artifact_manifest['files'][0]['bytes'], 'tensors': len(artifact_manifest['tensors']), 'policy': artifact_manifest['adapter']['policy']}},\n"
                "    'reload_parity': parity,\n"
                "    'runtime': {{'python': platform.python_version(), 'torch': torch.__version__, 'transformers': transformers.__version__, 'device': pipe.device, 'dtype': 'float32', 'source': pipe.source}},\n"
                "}}\n"
                "with open('outputs/{stem}_result.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(result_payload, handle, indent=2, ensure_ascii=False)\n"
                "print(sorted(os.listdir('outputs')))\n"
                "print({{'run_summary': run_summary}})"
            ),
        },
    ],
    "closing": (
        "**What to notice:** the two map pairs, the adapter's policy and tensor count, the reload-parity line, and "
        "the run summary printed last.\n\n"
        "<details><summary>Check your reasoning</summary>The adapter would hold the neck and head tensors as byte "
        "copies of the base, its manifest would say `no_op: true`, and the before and after maps would be identical: "
        "the checkpoint is a policy too, and exporting it changes nothing. At the defaults the unfreeze was kept, so in "
        "the recorded Colab T4 run (2026-10-03) the adapter held 100 tensors (25,127,700 bytes: the neck and head plus "
        "the last two blocks) and the reloaded pipeline gave an identical depth map and the same test AbsRel.</details>\n\n"
        "## 10. Your turn — change one thing: the learning rate\n\n"
        "Optional; **Predict → Change → Run → Observe → Explain**. It re-runs the ladder, so it takes about as long as "
        "Section 7 did.\n\n"
        "1. **Predict:** with `LEARNING_RATE = 3e-5` (three times the default), will the ladder still keep the "
        "unfreeze at its last epoch, or stop earlier? Will the held-out gain grow or shrink? Write your guess next to the "
        "default run's row in the Section 8 run history.\n"
        "2. **Change:** in Section 7 set `LEARNING_RATE = 3e-5`. Change nothing else.\n"
        "3. **Run:** select the Section 7 cell and choose **Runtime → Run after**. Section 7 reloads the pretrained "
        "model before adapting, Section 8 compares against the same Section 6 zero-shot score and adds a row to the run "
        "history, and Section 9 exports and reloads the new adapter.\n"
        "4. **Observe:** in Section 7, epoch 0 shows the *untouched* checkpoint's validation AbsRel again (about 0.243, "
        "not the adapted 0.130); in Section 8, the run history now has two rows — compare `best_epoch`, `selected` and "
        "`delta`; in Section 9, the adapter's policy and tensor count.\n"
        "5. **Explain:** in one sentence, why did a larger step size change which epoch the validation split kept?\n\n"
        "<details><summary>Check your reasoning</summary>It stops earlier. In a local CPU run of this notebook version (2026-10-03, 24-thread Windows workstation, real weights, default settings otherwise) the re-run printed epoch 0 at the untouched checkpoint's 0.2426, then validation AbsRel 0.1755 → 0.1382 (neck and head) → 0.1515 → 0.1429 → 0.1437 (unfrozen), so validation kept the **neck-and-head policy at epoch 2**; held-out AbsRel was 0.1750 (Δ −0.005 against 0.1800, 4 of 8 test views better and 4 worse), a smaller gain than the default run's −0.0131, and the adapter held 64 tensors (no backbone blocks) with exact reload parity. With three times the step size the neck and head fit the 24 views within two epochs, and the unfreeze at that rate made validation worse, so the selection rule kept the earlier epoch. If your epoch 0 did not show about 0.243, the model was not reset: restart the session and choose **Run all**.</details>\n\n"
        "## Interpretation and limits\n\n"
        "Start from your own run summary (the last line of Section 9): which policy did validation keep, and did it "
        "lower held-out AbsRel against the checkpoint? Then read the per-domain rows and the improved / worsened view "
        "counts before you believe the mean.\n\n"
        "<details><summary>Reference answer from the recorded runs</summary>The untouched Depth Anything V2 Small "
        "checkpoint already beats both priors by a wide margin on the eight DIODE test views (AbsRel 0.18 against 0.26 "
        "and 0.33). At the default settings the bounded adaptation on 24 training views — neck and head first, then the "
        "last two blocks, selected against the checkpoint by validation AbsRel — was selected at its last epoch and "
        "lowered held-out AbsRel from 0.1800 to 0.1669 in the recorded Colab T4 run (2026-10-03), almost all of it "
        "outdoors, with some test views worse after adaptation than before. On BYOD data or with other settings your "
        "numbers describe a different run; read them, not these.</details>\n\n"
        "What the notebook does establish is that the adaptation contract runs a three-policy ladder end to end on a real "
        "RGB-D corpus, lets the checkpoint win when it should, and reports the answer against two priors rather than in "
        "isolation. The test split is eight views from four scans of one seeded split of one small corpus with no "
        "dispersion estimate — one view is an eighth of every mean, and two views of one scan are nearly the same scene. "
        "AbsRel and δ1 are computed after a per-image affine alignment inside 0.6..350 m, so they say how well the "
        "*ordering and relative spacing* of depth match the laser reference, not whether any metre is right; the model's "
        "output stays relative after adaptation. The ladder's outcome is a property of this corpus and these "
        "hyperparameters, not of the method — Section 10 shows how much one hyperparameter moves it.\n\n"
        "Three things to carry to real data. **Priors first:** the constant and gradient priors on *your* depth maps "
        "are the numbers to read before any model's — a scene that a vertical gradient explains is not testing the "
        "model. **Leakage:** split by capture session, scan or device (the contract splits by `scan` / `group`, never by "
        "view). **Policy:** the untouched checkpoint is a policy too; keep it in the ladder and let validation decide, "
        "and keep the learning rate small — a 25 M-parameter model trained on 62 million images has little to learn "
        "from 24 views except your sensor's habits.\n\n"
        "Successful execution proves that the recorded repository revision's pipeline modules, carried in this standalone "
        "notebook, can acquire and digest-verify the pinned model snapshot, fetch and digest-verify a real RGB-D corpus, "
        "validate the demonstrated dataset contract without leakage, execute the inference contract with a "
        "`sample-sanity` metric against a laser reference, run the zero-shot, frozen and unfrozen policies with "
        "validation-based selection, evaluate by aligned AbsRel and δ1 against two priors on an independent split, and "
        "emit the shown machine-readable artifacts — without the repository being reachable. It does **not** establish "
        "benchmark superiority, metric accuracy, a usable acceptance threshold, or production fitness.\n\n"
        "**Optional experiments (they do not affect the default path).** Each one changes one form field; note the "
        "numbers you want to compare first (the Section 8 run history keeps one row per pass). In Colab, **Runtime → Run "
        "after** runs the selected cell and every cell below it; Sections 5, 6 and 7 reload the pretrained model before "
        "they use it, so no experiment inherits an earlier adaptation. Decide what you expect before each run, then "
        "compare with the reference answer.\n\n"
        "- **A hot unfreeze:** set `LEARNING_RATE = 1e-4` in Section 7, select Section 7 and choose **Run after**. Does "
        "the policy validation keeps also win on the held-out split? <details><summary>Reference answer</summary>In the "
        "build-record sweep (2026-09-19, not re-measured for this notebook version) the unfreeze was selected on "
        "validation and scored 0.186 on test — worse than the checkpoint's 0.180: validation on four scans can pick a "
        "model that does not transfer.</details>\n"
        "- **More trainable blocks:** set `TRAINABLE_BLOCKS = 4` in Section 7 and **Run after** from there. Does training "
        "more of the backbone help on 24 views? <details><summary>Reference answer</summary>In the build-record sweep "
        "(2026-09-19, not re-measured here) the neck-and-head policy was kept instead, at 0.175 on test: with more "
        "trainable parameters validation stopped before the unfreeze.</details>\n"
        "- **Longer unfreeze:** set `EPOCHS = 6` in Section 7 and **Run after** from there. Does validation AbsRel keep "
        "falling? (The best epoch is kept either way; no reference answer is recorded.)\n"
        "- **No adaptation at all:** set `HEAD_EPOCHS = 0` and `EPOCHS = 0` in Section 7 and **Run after** from there. "
        "What will the run summary and the adapter show? <details><summary>Reference answer</summary>Only epoch 0 "
        "exists, so the checkpoint is selected, the run summary shows a delta of 0 with all 8 views unchanged, and "
        "Section 9 exports a `no_op` adapter that reloads with parity (checked in a local CPU run of this notebook "
        "version, 2026-10-03).</details>\n"
        "- **Your own RGB-D records:** BYOD (Section 4, then **Run after**); read the priors and the zero-shot row before "
        "either adapted policy.\n\n"
        "## Troubleshooting\n\n"
        "- **Section 1 stops with \"needs a Linux x86_64 runtime\".** The locked environment is built from manylinux "
        "wheels. Use Google Colab, Kaggle or a Linux Jupyter server; Windows and macOS kernels are not supported.\n"
        "- **Section 1 fails while downloading** (`uv` wheel, Python build or packages). The runtime needs PyPI and the "
        "python-build-standalone download; run the cell again once the network is back. A \"size/SHA-256\" or \"does not "
        "match its digest\" error means a file was altered: do not edit the cell, regenerate the notebook from the "
        "repository.\n"
        "- **A restart prompt.** This notebook never needs a runtime restart: nothing is installed into the kernel. If "
        "the runtime restarted anyway (you chose it, or it was reset), choose **Run all** again from the top; files "
        "already downloaded and verified are reused while they are still there.\n"
        "- **\"The isolated environment's Python process exited\".** Usually the runtime ran out of memory. Restart the "
        "session and choose **Run all**; on CPU, close other notebooks first.\n"
        "- **Section 3 or 4 stops on a download** (the Hub snapshot, or a `206 Partial Content` / `Content-Range` error "
        "from the ETH archive). The server was unreachable or answered with something other than the pinned byte range; "
        "run the cell again later. Files already verified are kept under `weights/` and are not fetched twice.\n"
        "- **A digest or size mismatch in Section 3 or 4.** A download was incomplete or altered; the notebook refuses it "
        "rather than continuing. Run the cell again; never edit the manifest or the corpus digests.\n"
        "- **Out of disk or memory.** The locked install, the 99 MB checkpoint and the 312 MB of DIODE files need a few "
        "GB of free disk; the ladder trains on one view at a time. Start a fresh runtime, or delete `dimer_isolated_env/` "
        "and `weights/` from an earlier attempt.\n"
        "- **BYOD is refused in Section 4.** The message names what to fix: fewer than 4 distinct groups, a split left "
        "empty or with fewer than 4 training views, a row without a `group`, a missing `records.csv` or column, a "
        "duplicate id, a depth map of the wrong shape or a mask with too few valid pixels. Fix the set and run Section 4 "
        "with **Run after** again. An empty or cancelled upload asks you to choose one file or set `BYOD_PATH`.\n"
        "- **Section 6 or 8 stops on an assertion about the priors.** The checkpoint (or the selected model) did not beat "
        "a trivial prior on your test views: read the printed rows — your depth maps may be explained by a vertical "
        "gradient, or be mis-paired or mis-scaled.\n"
        "- **Reload parity fails in Section 9.** The saved adapter does not reproduce the evaluated model. Re-run from "
        "Section 7 (it reloads the pretrained model first), or restart the session and choose **Run all**.\n"
        "- **Numbers differ slightly from the recorded runs.** GPU arithmetic is not bit-for-bit the CPU's: a difference "
        "of 0.0001 in a per-domain or per-view AbsRel between a T4 and a CPU run is expected. Larger differences on the "
        "default settings mean a form field was changed.\n\n"
        "## Glossary\n\n"
        "- **Relative inverse depth:** what the model outputs — larger = nearer, with an unknown scale and shift; not "
        "metres.\n"
        "- **Metric depth:** distance in metres, here from DIODE's laser scanner; the reference the prediction is scored "
        "against.\n"
        "- **Alignment:** the per-image least-squares scale and shift that maps the prediction onto inverse reference "
        "depth before scoring, because a relative model's scale and shift are free.\n"
        "- **AbsRel:** mean absolute relative error, |predicted − reference| / reference over the scored pixels after "
        "alignment; lower is better.\n"
        "- **δ1:** the share of scored pixels whose aligned prediction is within a factor of 1.25 of the reference; higher "
        "is better.\n"
        "- **Validity mask:** the pixels where the scanner returned a depth; only those inside 0.6..350 m are scored.\n"
        "- **Constant / vertical-gradient prior:** two trivial predictions (every pixel at the median depth; nearer at the "
        "bottom) that frame what a model must beat.\n"
        "- **Backbone / transformer block:** the DINOv2 ViT-S/14 image encoder, a stack of 12 blocks; the last "
        "`TRAINABLE_BLOCKS` can be unfrozen.\n"
        "- **DPT neck and head:** the layers that turn backbone features into the full-resolution depth map; the frozen "
        "policy trains only these.\n"
        "- **Policy:** which parameters are trained — zero-shot (none), frozen (neck and head), unfrozen (neck, head and "
        "the last blocks).\n"
        "- **Epoch / epoch 0:** one pass over the training views; epoch 0 is the untouched checkpoint, scored before any "
        "training so it can win.\n"
        "- **Training / validation / test split:** views used to train, to choose the epoch, and to report the final "
        "result once — split by scan.\n"
        "- **Adapter / reload parity:** the saved trained tensors, and the check that a pipeline rebuilt from them gives "
        "the same depth map and AbsRel.\n\n"
        "## Conclusion (your notes)\n\n"
        "Optional personal notes, not a required submission. Complete each sentence from your own run:\n\n"
        "- On these test views the constant prior scored AbsRel ___, the gradient prior ___, the checkpoint ___ and the "
        "selected policy (___) ___.\n"
        "- The adaptation improved ___ and worsened ___ of the test views; most of the change was in the ___ domain.\n"
        "- With `LEARNING_RATE = ___` (Section 10) validation kept epoch ___ and the held-out AbsRel was ___, because "
        "___.\n"
        "- Before trusting an adapted depth model on my own images I would measure ___ on ___.\n\n"
        "## References\n\n"
        "- Repository README: https://github.com/kurtvalcorza/depth-anything-depth-estimation-pipeline/blob/main/README.md\n"
        "- Repository model card: https://github.com/kurtvalcorza/depth-anything-depth-estimation-pipeline/blob/main/MODEL_CARD.md\n"
        "- Weight provenance: https://github.com/kurtvalcorza/depth-anything-depth-estimation-pipeline/blob/main/docs/WEIGHTS.md\n"
        "- Upstream model: https://huggingface.co/{MODEL_ID}\n"
        "- Upstream code: https://github.com/DepthAnything/Depth-Anything-V2\n"
        "- Depth Anything V2 paper (Yang et al., 2024): https://arxiv.org/abs/2406.09414\n"
        "- DIODE: A Dense Indoor and Outdoor DEpth Dataset (Vasiljevic et al., 2019; CC BY 4.0): https://diode-dataset.org — https://arxiv.org/abs/1908.00463\n"
        "- Marigold evaluation dataset archive (ETH Zürich PRS) serving the pinned DIODE files: https://share.phys.ethz.ch/~pf/bingkedata/marigold/evaluation_dataset/diode/diode_val.tar\n"
        "- Towards Robust Monocular Depth Estimation (MiDaS; the scale-and-shift-invariant loss and aligned evaluation, Ranftl et al., 2020): https://arxiv.org/abs/1907.01341\n"
        "- Transformers `DepthAnything` documentation: https://huggingface.co/docs/transformers/model_doc/depth_anything\n"
        "- DIMER Notebook Specification 2.2 and Model Card Specification 1.1 (fleet specs in the ml-worker repository)"
    ),
}
